### ISSUE TITLE
HOME: event details/header illustration

### ISSUE THREAD

**Issue by rwathree** [risd/risd-commencement#25]
Date/time/location info overlaps header illustration; hard to read.

![screen shot 2018-02-02 at 2 51 28 pm](https://user-images.githubusercontent.com/25105727/35752082-a2c1e76c-0828-11e8-9075-f67fada5fc4f.png)

**Comment by mmarol** [comment]
This is currently dependent on the window size. I'm going to tweak it once I get the animation from Karen.
